app/core/static/js/candidates.js

Removed fadeIn/fadeOut
Positioning using jQuery UI position function instead of manual mouse position

Fixes some hover issues on candidate list

---

README.md
app/core/management/commands/generate_politicians.py
app/core/management/commands/politician_import.py
app/core/management/commands/user_import.py
politician_import.csv.example
user_import.csv.example

By improving the `app/manage.py help <cmd>` output, and by providing
`.example` files, the possibilities of the management commands are more
clear.
This relates to issue: https://github.com/adfinis-sygroup/freedomvote/issues/24

doc(management): improved management documentation

---

doc/HOWTO.md
doc/README.md

Generic documentation to give insight in the best practices and work to
consider when running with Freedomvote. This includes the technical
parts but more importantly the organization effort is included.
Related issue: https://github.com/adfinis-sygroup/freedomvote/issues/34

doc(howto): how to do freedomvote

---

app/freedomvote/settings.py
app/locale/en/LC_MESSAGES/django.po
app/locale/fr/LC_MESSAGES/django.po
app/locale/it/LC_MESSAGES/django.po
app/locale/nl/LC_MESSAGES/django.po

Both English and Dutch translations for Freedomvote.
Issue for English: https://github.com/freedomvote/freedomvote/issues/20
Issue for Dutch:   https://github.com/freedomvote/freedomvote/issues/19

feat(translations): EN and NL translations

---

app/freedomvote/settings.py

Fixed the language selection by removing a middleware of the cms

---

.gitignore
README.md
app/core/management/commands/politician_import.py
app/core/management/commands/user_import.py
app/core/migrations/0005_auto_20161216_1206.py
app/core/models.py
examples/politician_import.json
examples/user_import.json
politician_import.csv.example
user_import.csv.example

Converted CSV import to JSON import and moved examples to own folder

---

app/api/util.py
app/api/views.py

All translations (django settings) of the model fields are in the api view.
resolves #51

All model field translation in api view.

---

app/core/templates/core/profile/description.html

Added a if/else to check if the politician party is set and if not it will print out the politician 'other' field.
Fix #52

Check if politician party is present.

---

app/core/migrations/0004_auto_20161219_0855.py

Added the missing migration file to remove the linktype field.
Related to PR #50 and Issue #11

Missing Migrationfile

---

tools/email/README.md
tools/email/gen_mails.py
tools/email/party_account_template_de.eml
tools/email/party_account_template_de_raw.txt
tools/email/party_accounts_example.csv

Based on the templates and scripts used during the Swiss Freedomvote campaign.
Related issue: https://github.com/freedomvote/freedomvote/issues/39

feat(email): email generation tool

---

app/core/static/js/profile_spider_embed.js
app/core/templates/core/profile/spider_embed.html

Credits on the bottom right corner.

Freedomvote credits on embedable spider graphic

---

app/templates/navbar.html

Language codes in uppercase

---

app/core/views.py

Check if column item is none to prevent a exception

---

app/core/templates/core/party/dashboard.html

Add direct edit link to politician

---

app/locale/en/LC_MESSAGES/django.po

fix a typo in the english translation

---

app/core/templates/core/compare/index.html
app/core/views.py

Still needs some work. 
PR will resolve #92

Combine save and evaluate

---

README.md

Informs users on how to define which database user to use.

Little enhancement to the README

---

app/core/templatetags/party.py
app/core/views.py

* Use unicode strings
* Add party long name as title on the party icon

Fix minor issues

---

Dockerfile
app/api/urls.py
app/core/admin.py
app/core/models.py
app/core/urls.py
app/core/views.py
app/core/widgets.py
app/freedomvote/settings.py
app/freedomvote/urls.py
docker-compose.yml
requirements.txt

Update django version

---

Dockerfile
app/api/urls.py
app/core/admin.py
app/core/models.py
app/core/templatetags/tags.py
app/core/urls.py
app/core/views.py
app/core/widgets.py
app/freedomvote/settings.py
app/freedomvote/urls.py
docker-compose.yml
requirements.txt

Please merge #158 and #159 first

Update pillow version and fix python syntax

---

Dockerfile
app/api/urls.py
app/core/admin.py
app/core/forms.py
app/core/models.py
app/core/templatetags/helpers.py
app/core/templatetags/tags.py
app/core/urls.py
app/core/views.py
app/core/widgets.py
app/freedomvote/settings.py
app/freedomvote/urls.py
docker-compose.yml
requirements.txt

Please merge #158, #159, #160 first

Update psycopg django meta and django restframework

---

app/core/static/js/candidates.js

If the own opinion is activated, list the candidates according to the own opinion.

fix(listing): list candidates not randomly
